DATASET:
  root_dataset: "/Data/1_17_clear_wet_day"
  list_train: "/Data/1_17_clear_wet_day/odgt/train.odgt"
  list_val: "/Data/1_17_clear_wet_day/odgt/validate.odgt"
  num_class: 29
  imgSizes: (360, 540, 720)  # Smaller sizes
  imgMaxSize: 960
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "mobilenetv2dilated"
  arch_decoder: "ppm_deepsup"
  fc_dim: 320

TRAIN:
  batch_size_per_gpu: 2
  num_epoch: 20
  start_epoch: 0
  epoch_iters: 5000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: True
  checkpoint: "epoch_20.pth"

TEST:
  checkpoint: "epoch_20.pth"
  result: "./"

DIR: "ckpt/ade20k-mobilenetv2dilated-ppm_deepsup-CARLADAYCLEAR"
