DATASET:
  root_dataset: "/Data/toledod/collectedData/trafficPath"
  list_train: "/Data/toledod/collectedData/trafficPath/odgt_BZ/train.odgt"
  list_val: "/Data/toledod/collectedData/trafficPath/odgt_BZ/validate.odgt"
  num_class: 29
  imgSizes: (500, 600, 700)
  imgMaxSize: 800
  padding_constant: 8
  segm_downsampling_rate: 8
  random_flip: True

MODEL:
  arch_encoder: "mobilenetv2dilated"
  arch_decoder: "c1_deepsup"
  fc_dim: 320

TRAIN:
  batch_size_per_gpu: 3
  num_epoch: 20
  start_epoch: 0
  epoch_iters: 5000
  optim: "SGD"
  lr_encoder: 0.02
  lr_decoder: 0.02
  lr_pow: 0.9
  beta1: 0.9
  weight_decay: 1e-4
  deep_sup_scale: 0.4
  fix_bn: False
  workers: 16
  disp_iter: 20
  seed: 304

VAL:
  visualize: True 
  checkpoint: "epoch_20.pth"

TEST:
  checkpoint: "epoch_20.pth"
  result: "./"

DIR: "ckpt/ade20k-mobilenetv2dilated-c1_deepsup-customCarla2"
